[project]
name = "claim"
requires-python = "3.11"


[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
dependencies.file = ["requirements.in"]

[tool.ruff]
line-length = 99


[tool.pytest.ini_options]
pythonpath = ["src"]
